import { Theme } from './types';

export const themes: Record<string, Theme> = {
  default: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '16px',
        borderRadius: '8px',
        border: '1px solid var(--gray-4)',
        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
      },
      title: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'var(--gray-12)',
        marginBottom: '8px',
        lineHeight: '1.3',
      },
      description: {
        color: 'var(--gray-11)',
        fontSize: '13px',
        lineHeight: '1.4',
        marginBottom: '12px',
      },
    },
    field: {
      container: {
        marginBottom: '12px',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '500',
        color: 'var(--gray-12)',
      },
      input: {
        width: '100%',
        padding: '8px 12px',
        borderRadius: '6px',
        border: '1px solid var(--gray-6)',
        fontSize: '13px',
        backgroundColor: 'white',
        transition: 'all 0.2s',
        '&:focus': {
          borderColor: 'var(--blue-8)',
          outline: 'none',
          boxShadow: '0 0 0 2px var(--blue-3)',
        },
        '&:hover': {
          borderColor: 'var(--gray-8)',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      },
    },
    button: {
      padding: '8px 14px',
      backgroundColor: 'var(--blue-9)',
      color: 'white',
      border: 'none',
      borderRadius: '6px',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'all 0.2s',
      boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
      '&:hover': {
        backgroundColor: 'var(--blue-10)',
        transform: 'translateY(-1px)',
        boxShadow: '0 2px 3px rgba(0, 0, 0, 0.1)',
      },
      '&:active': {
        opacity: 0.9,
        transform: 'translateY(0)',
      },
    },
  },

  modern: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '18px',
        borderRadius: '8px',
        border: '1px solid var(--gray-5)',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
        background: 'linear-gradient(to bottom, var(--gray-1), white)',
      },
      title: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'var(--gray-12)',
        marginBottom: '8px',
        letterSpacing: '-0.02em',
        lineHeight: '1.2',
      },
      description: {
        color: 'var(--gray-11)',
        fontSize: '13px',
        lineHeight: '1.5',
        marginBottom: '14px',
      },
    },
    field: {
      container: {
        marginBottom: '12px',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '500',
        color: 'var(--gray-12)',
        letterSpacing: '-0.01em',
      },
      input: {
        width: '100%',
        padding: '8px 12px',
        borderRadius: '6px',
        border: '1px solid var(--gray-5)',
        fontSize: '13px',
        backgroundColor: 'white',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.03)',
        transition: 'all 0.2s',
        '&:focus': {
          borderColor: 'var(--gray-8)',
          outline: 'none',
          boxShadow: '0 0 0 2px var(--gray-4), 0 2px 4px rgba(0, 0, 0, 0.03)',
        },
        '&:hover': {
          borderColor: 'var(--gray-7)',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      },
    },
    button: {
      padding: '8px 16px',
      backgroundColor: 'var(--gray-12)',
      color: 'white',
      border: 'none',
      borderRadius: '6px',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'all 0.2s',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.12)',
      '&:hover': {
        backgroundColor: 'var(--gray-11)',
        transform: 'translateY(-1px)',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.15)',
      },
      '&:active': {
        transform: 'translateY(1px)',
        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
      },
    },
  },

  neobrutalism: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '16px',
        border: '2px solid black',
        borderRadius: '0',
        boxShadow: '4px 4px 0 black',
        position: 'relative',
      },
      title: {
        fontSize: '18px',
        fontWeight: '800',
        color: 'black',
        marginBottom: '6px',
        textTransform: 'uppercase',
        letterSpacing: '-0.01em',
        position: 'relative',
      },
      description: {
        color: 'black',
        fontSize: '13px',
        fontFamily: 'monospace',
        marginBottom: '12px',
        lineHeight: '1.4',
        position: 'relative',
      },
    },
    field: {
      container: {
        marginBottom: '12px',
        position: 'relative',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '800',
        color: 'black',
        textTransform: 'uppercase',
      },
      input: {
        width: '100%',
        padding: '8px 10px',
        border: '2px solid black',
        borderRadius: '0',
        boxShadow: '2px 2px 0 black',
        fontSize: '13px',
        fontFamily: 'monospace',
        transition: 'transform 0.1s, box-shadow 0.1s',
        '&:focus': {
          transform: 'translate(-2px, -2px)',
          boxShadow: '4px 4px 0 black',
          outline: 'none',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
        fontWeight: '700',
        textTransform: 'uppercase',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      },
    },
    button: {
      padding: '8px 14px',
      backgroundColor: 'var(--yellow-4)',
      color: 'black',
      border: '2px solid black',
      borderRadius: '0',
      fontWeight: '800',
      fontSize: '13px',
      cursor: 'pointer',
      boxShadow: '2px 2px 0 black',
      textTransform: 'uppercase',
      transition: 'transform 0.1s, box-shadow 0.1s',
      '&:hover': {
        backgroundColor: 'var(--yellow-5)',
      },
      '&:active': {
        transform: 'translate(2px, 2px)',
        boxShadow: '0px 0px 0 black',
      },
    },
  },

  simple: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '14px',
      },
      title: {
        fontSize: '16px',
        fontWeight: '500',
        color: 'var(--gray-12)',
        marginBottom: '6px',
        lineHeight: '1.3',
      },
      description: {
        color: 'var(--gray-11)',
        fontSize: '13px',
        lineHeight: '1.4',
        marginBottom: '12px',
      },
    },
    field: {
      container: {
        marginBottom: '10px',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '400',
        color: 'var(--gray-11)',
      },
      input: {
        width: '100%',
        padding: '6px 10px',
        borderRadius: '4px',
        border: '1px solid var(--gray-6)',
        fontSize: '13px',
        transition: 'border-color 0.15s',
        '&:focus': {
          borderColor: 'var(--gray-8)',
          outline: 'none',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
      },
    },
    button: {
      padding: '6px 12px',
      backgroundColor: 'var(--gray-9)',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      fontWeight: '500',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'background-color 0.15s',
      '&:hover': {
        backgroundColor: 'var(--gray-10)',
      },
    },
  },
}; 