import { Theme } from './types';

export const themes: Record<string, Theme> = {
  // For each theme in the themes object, modify the form.container property
  default: {
    form: {
      container: {
        maxWidth: '480px',
        width: '100%',
        margin: '0 auto',
        padding: '24px',
        borderRadius: '12px',
        border: '1px solid var(--gray-4)',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
        backgroundColor: 'white',
        backdropFilter: 'blur(8px)', // Adds a blur effect behind the form
      },
      containerDark: {
        maxWidth: '480px',
        width: '100%',
        margin: '0 auto',
        padding: '24px',
        borderRadius: '12px',
        border: '1px solid var(--gray-8)',
        boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
        backgroundColor: '#1a1a1a',
        backdropFilter: 'blur(8px)',
      },
      title: {
        fontSize: '22px',
        fontWeight: '700',
        color: 'black',
        marginBottom: '12px',
        lineHeight: '1.3',
        letterSpacing: '-0.02em',
      },
      titleDark: {
        fontSize: '22px',
        fontWeight: '700',
        color: 'white',
        marginBottom: '12px',
        lineHeight: '1.3',
        letterSpacing: '-0.02em',
      },
      description: {
        color: 'var(--gray-20)',
        fontSize: '14px',
        lineHeight: '1.5',
        marginBottom: '20px',
      },
      descriptionDark: {
        color: 'white',
        fontSize: '14px',
        lineHeight: '1.5',
        marginBottom: '20px',
      },
    },
    field: {
      container: {
        marginBottom: '16px',
      },
      label: {
        display: 'block',
        marginBottom: '6px',
        fontSize: '14px',
        fontWeight: '500',
        color: 'black',
        letterSpacing: '-0.01em',
      },
      labelDark: {
        display: 'block',
        marginBottom: '6px',
        fontSize: '14px',
        fontWeight: '500',
        color: 'white',
        letterSpacing: '-0.01em',
      },
      input: {
        width: '100%',
        padding: '10px 14px',
        borderRadius: '8px',
        border: '1.5px solid var(--gray-6)',
        fontSize: '14px',
        backgroundColor: 'white',
        color: 'black', // Explicitly set text color to black
        transition: 'all 0.2s ease',
        '&:focus': {
          borderColor: 'var(--blue-8)',
          outline: 'none',
          boxShadow: '0 0 0 3px var(--blue-3)',
        },
        '&:hover': {
          borderColor: 'var(--gray-8)',
        },
        '&::placeholder': {
          color: 'var(--gray-9)',
        },
      },
      inputDark: {
        width: '100%',
        padding: '10px 14px',
        borderRadius: '8px',
        border: '1.5px solid var(--gray-8)',
        fontSize: '14px',
        backgroundColor: '#2a2a2a',
        color: 'white',
        transition: 'all 0.2s ease',
        '&:focus': {
          borderColor: 'var(--blue-8)',
          outline: 'none',
          boxShadow: '0 0 0 3px var(--blue-3)',
        },
        '&:hover': {
          borderColor: 'var(--gray-6)',
        },
        '&::placeholder': {
          color: '#a1a1aa',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '13px',
        marginTop: '6px',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: '500',
      },
    },
    button: {
      padding: '10px 18px',
      backgroundColor: 'var(--blue-9)',
      color: 'white',
      border: 'none',
      borderRadius: '8px',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.08)',
      width: '100%',
      marginTop: '8px',
      '&:hover': {
        backgroundColor: 'var(--blue-10)',
        transform: 'translateY(-1px)',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.12)',
      },
      '&:active': {
        transform: 'translateY(0)',
        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.08)',
      },
      '&:disabled': {
        opacity: 0.6,
        cursor: 'not-allowed',
        transform: 'none',
        boxShadow: 'none',
      },
      '&.order': {
        backgroundColor: 'var(--green-9)',
        '&:hover': {
          backgroundColor: 'var(--green-10)',
        },
      },
    },
  },

  modern: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '18px',
        borderRadius: '8px',
        border: '1px solid var(--gray-5)',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
        backgroundColor: 'white',
      },
      containerDark: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '18px',
        borderRadius: '8px',
        border: '1px solid var(--gray-8)',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
        backgroundColor: '#1a1a1a',
      },
      title: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'black',
        marginBottom: '8px',
        letterSpacing: '-0.02em',
        lineHeight: '1.2',
      },
      titleDark: {
        fontSize: '18px',
        fontWeight: '600',
        color: 'white',
        marginBottom: '8px',
        letterSpacing: '-0.02em',
        lineHeight: '1.2',
      },
      description: {
        color: 'var(--gray-20)',
        fontSize: '13px',
        lineHeight: '1.5',
        marginBottom: '14px',
      },
      descriptionDark: {
        color: 'white',
        fontSize: '13px',
        lineHeight: '1.5',
        marginBottom: '14px',
      },
    },
    field: {
      container: {
        marginBottom: '12px',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '500',
        color: 'black',
        letterSpacing: '-0.01em',
      },
      labelDark: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '500',
        color: 'white',
        letterSpacing: '-0.01em',
      },
      input: {
        width: '100%',
        padding: '8px 12px',
        borderRadius: '6px',
        border: '1px solid var(--gray-5)',
        fontSize: '13px',
        color: 'black', // Explicitly set text color to black
        backgroundColor: 'white',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.03)',
        transition: 'all 0.2s',
        '&:focus': {
          borderColor: 'var(--gray-8)',
          outline: 'none',
          boxShadow: '0 0 0 2px var(--gray-4), 0 2px 4px rgba(0, 0, 0, 0.03)',
        },
        '&:hover': {
          borderColor: 'var(--gray-7)',
        },
      },
      inputDark: {
        width: '100%',
        padding: '8px 12px',
        borderRadius: '6px',
        border: '1px solid var(--gray-8)',
        fontSize: '13px',
        color: 'white',
        backgroundColor: '#2a2a2a',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
        transition: 'all 0.2s',
        '&:focus': {
          borderColor: 'var(--gray-6)',
          outline: 'none',
          boxShadow: '0 0 0 2px var(--gray-7), 0 2px 4px rgba(0, 0, 0, 0.2)',
        },
        '&:hover': {
          borderColor: 'var(--gray-7)',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      },
    },
    button: {
      padding: '8px 16px',
      backgroundColor: 'black',
      color: 'white',
      border: 'none',
      borderRadius: '6px',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'all 0.2s',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.12)',
      '&:hover': {
        backgroundColor: 'var(--gray-20)',
        transform: 'translateY(-1px)',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.15)',
      },
      '&:active': {
        transform: 'translateY(1px)',
        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
      },
    },
  },

  neobrutalism: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '16px',
        border: '2px solid black',
        borderRadius: '0',
        boxShadow: '4px 4px 0 black',
        backgroundColor: 'white',
        position: 'relative',
      },
      containerDark: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '16px',
        border: '2px solid white',
        borderRadius: '0',
        boxShadow: '4px 4px 0 white',
        backgroundColor: '#1a1a1a',
        position: 'relative',
      },
      title: {
        fontSize: '18px',
        fontWeight: '800',
        color: 'black',
        marginBottom: '6px',
        textTransform: 'uppercase',
        letterSpacing: '-0.01em',
        position: 'relative',
      },
      titleDark: {
        fontSize: '18px',
        fontWeight: '800',
        color: 'white',
        marginBottom: '6px',
        textTransform: 'uppercase',
        letterSpacing: '-0.01em',
        position: 'relative',
      },
      description: {
        color: 'black',
        fontSize: '13px',
        fontFamily: 'monospace',
        marginBottom: '12px',
        lineHeight: '1.4',
        position: 'relative',
      },
      descriptionDark: {
        color: 'white',
        fontSize: '13px',
        fontFamily: 'monospace',
        marginBottom: '12px',
        lineHeight: '1.4',
        position: 'relative',
      },
    },
    field: {
      container: {
        marginBottom: '12px',
        position: 'relative',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '800',
        color: 'black',
        textTransform: 'uppercase',
      },
      labelDark: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '800',
        color: 'white',
        textTransform: 'uppercase',
      },
      input: {
        width: '100%',
        padding: '8px 10px',
        border: '2px solid black',
        borderRadius: '0',
        color: 'black', // Explicitly set text color to black
        boxShadow: '2px 2px 0 black',
        fontSize: '13px',
        fontFamily: 'monospace',
        transition: 'transform 0.1s, box-shadow 0.1s',
        '&:focus': {
          transform: 'translate(-2px, -2px)',
          boxShadow: '4px 4px 0 black',
          outline: 'none',
        },
      },
      inputDark: {
        width: '100%',
        padding: '8px 10px',
        border: '2px solid white',
        borderRadius: '0',
        color: 'white',
        backgroundColor: '#1a1a1a',
        boxShadow: '2px 2px 0 white',
        fontSize: '13px',
        fontFamily: 'monospace',
        transition: 'transform 0.1s, box-shadow 0.1s',
        '&:focus': {
          transform: 'translate(-2px, -2px)',
          boxShadow: '4px 4px 0 white',
          outline: 'none',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
        fontWeight: '700',
        textTransform: 'uppercase',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
      },
    },
    button: {
      padding: '8px 14px',
      backgroundColor: 'var(--yellow-4)',
      color: 'black',
      border: '2px solid black',
      borderRadius: '0',
      fontWeight: '800',
      fontSize: '13px',
      cursor: 'pointer',
      boxShadow: '2px 2px 0 black',
      textTransform: 'uppercase',
      transition: 'transform 0.1s, box-shadow 0.1s',
      '&:hover': {
        backgroundColor: 'var(--yellow-5)',
      },
      '&:active': {
        transform: 'translate(2px, 2px)',
        boxShadow: '0px 0px 0 black',
      },
    },
  },

  simple: {
    form: {
      container: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '14px',
        backgroundColor: 'white',
      },
      containerDark: {
        maxWidth: '380px',
        margin: '0 auto',
        padding: '14px',
        backgroundColor: '#1a1a1a',
      },
      title: {
        fontSize: '16px',
        fontWeight: '500',
        color: 'black',
        marginBottom: '6px',
        lineHeight: '1.3',
      },
      titleDark: {
        fontSize: '16px',
        fontWeight: '500',
        color: 'white',
        marginBottom: '6px',
        lineHeight: '1.3',
      },
      description: {
        color: 'var(--gray-20)',
        fontSize: '13px',
        lineHeight: '1.4',
        marginBottom: '12px',
      },
      descriptionDark: {
        color: 'white',
        fontSize: '13px',
        lineHeight: '1.4',
        marginBottom: '12px',
      },
    },
    field: {
      container: {
        marginBottom: '10px',
      },
      label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '400',
        color: 'black',
      },
      labelDark: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '13px',
        fontWeight: '400',
        color: 'white',
      },
      input: {
        width: '100%',
        padding: '6px 10px',
        borderRadius: '4px',
        color: 'black', // Explicitly set text color to black
        border: '1px solid var(--gray-6)',
        fontSize: '13px',
        transition: 'border-color 0.15s',
        '&:focus': {
          borderColor: 'var(--gray-8)',
          outline: 'none',
        },
      },
      inputDark: {
        width: '100%',
        padding: '6px 10px',
        borderRadius: '4px',
        color: 'white',
        backgroundColor: '#2a2a2a',
        border: '1px solid var(--gray-8)',
        fontSize: '13px',
        transition: 'border-color 0.15s',
        '&:focus': {
          borderColor: 'var(--gray-6)',
          outline: 'none',
        },
      },
      error: {
        color: 'var(--red-9)',
        fontSize: '12px',
        marginTop: '4px',
      },
    },
    button: {
      padding: '6px 12px',
      backgroundColor: 'var(--gray-9)',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      fontWeight: '500',
      fontSize: '13px',
      cursor: 'pointer',
      transition: 'background-color 0.15s',
      '&:hover': {
        backgroundColor: 'var(--gray-10)',
      },
    },
  },
};