export { default as Slack } from './Slack'
export { default as Discord } from './DiscordLogo'
export { default as MagicUI } from './MagicUI'
export { default as VSCodium } from './VSCodium'
export { default as MediaWiki } from './MediaWiki'
export { default as Resend } from './Resend'
