name: Security

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs-site/**'
      - 'mantlz-sdk/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs-site/**'
      - 'mantlz-sdk/**'
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: |
        # Remove docs-site and mantlz-sdk from the audit
        rm -rf docs-site mantlz-sdk
        npm audit

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Mantle'
        path: '.'
        format: 'HTML'
        out: 'reports' 